### ISSUE TITLE
CLI v1.1.0+ doesn't read `tsconfig.json` when `--project` is not specified

### ISSUE THREAD

**Issue by heguro** [line/tsr#102]
## Current behavior

Initialize [my repository for reproduce](https://github.com/heguro/20241216-tsr-test):

```console
$ git clone https://github.com/heguro/20241216-tsr-test
$ cd 20241216-tsr-test
$ npm i
```

When running `tsr` without `--project`: Incorrect output, doesn't read tsconfig.json

```console
$ npx tsr 'main\.ts$'
tsconfig using default options
Project has 3 files. Found 1 entrypoint file
file   src/app/app.ts
file   src/fn/util.ts
✖ delete 2 files
```

When running `tsr` with `--project`: Correct output

```console
$ npx tsr -p tsconfig.json 'main\.ts$'
tsconfig tsconfig.json
Project has 3 files. Found 1 entrypoint file
export src/fn/util.ts:4:0     'unusedFunc'
✖ remove 1 export
```

## Root Cause

- In the new CLI implementation released in v1.1.0, `--project`'s default value is `''`, not `undefined` or `'tsconfig.json'`.
  - https://github.com/line/tsr/blob/83a7f3bb9c6e7ec9720dad00bca0d0e1024d1349/lib/cli.ts#L8-L15
- While `'tsconfig.json'` is set as the default value for the `configFile` parameter in the `tsr` function, it is not used when `''` is passed.
  - https://github.com/line/tsr/blob/83a7f3bb9c6e7ec9720dad00bca0d0e1024d1349/lib/cli.ts#L104
  - https://github.com/line/tsr/blob/83a7f3bb9c6e7ec9720dad00bca0d0e1024d1349/lib/tsr.ts#L41
- This generates an incorrect `configPath`, causing `ts.readConfigFile()` to fail.

**Comment by kazushisan** [comment]
@heguro thank you very much for the detailed report! I've fixed this issue in https://github.com/line/tsr/releases/tag/v1.3.1

**Comment by kazushisan** [comment]
added test cases to prevent future degrade in https://github.com/line/tsr/pull/107
